name: Build CPython Windows x64 Embed NoGIL
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "CPython tag (e.g. v3.12.13)"
        required: true
        default: "v3.12.13"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout CPython
        uses: actions/checkout@v4
        with:
          repository: python/cpython
          ref: ${{ github.event.inputs.tag }}

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build using official release script
        shell: cmd
        env:
          IncludeFreethreaded: "true"
          UseDisableGil: "true"
        run: |
          Tools\msi\buildrelease.bat -x64 --skip-msi --skip-nuget --skip-doc

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-${{ github.event.inputs.tag }}-windows-x64-nogil
          path: D:\a\python_build\python_build
