name: CPython Windows x64 NoGIL
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "CPython tag (e.g. v3.14.4)"
        required: true
        default: "v3.14.4"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout CPython
        uses: actions/checkout@v4
        with:
          repository: python/cpython
          ref: ${{ github.event.inputs.tag }}

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
    
      - name: Build using official release script
        shell: cmd
        env:
          IncludeFreethreaded: "true"
          UseDisableGil: "true"
          DisableGil: "true"
          do_pgo: "true"
        run: |
          Tools\msi\buildrelease.bat -x64 --skip-msi --skip-nuget --skip-doc --skip-zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-${{ github.event.inputs.tag }}t-windows-x64
          path: |
            PCbuild\amd64\python*.dll
            PCbuild\amd64\python*.exe
